---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-lite-ci

inputs:
- name: bosh-cpi-release
- name: version-semver
outputs:
- name: candidate
run:
  path: bosh-cpi-release/ci/tasks/build-candidate.sh
