---
platform: linux
image: docker:///posijon/slci

inputs:
  - name: bosh-softlayer-cpi-release
    path: gopath/src/github.com/maximilien/bosh-softlayer-cpi-release
  - name: version

run:
  path: gopath/src/github.com/maximilien/bosh-softlayer-cpi-release/bin/build